### ISSUE TITLE
Can't Save Files Outside /home in Linux Mint

### ISSUE THREAD

**Issue by nhtctn** [vcprocles/aegisub-procles-snap#2]
Hello. I am a begginer with linux. I am using Linux Mint 21 Cinnamon 5.4.12 . I generally store my susbtitles in external hard drives. When i first install snap, i can't open subtitles with aegisub. With solution below, aegisub became able to open subtitles.

https://askubuntu.com/questions/1228899/how-to-access-files-outside-of-home-in-snap-apps
`sudo snap connect aegisub-procles:removable-media`

It opens but can't change. It only preview subtitle. When i make a change, the save button won't activated. Is there any way to edit subtitles outside of /home?

Not: There is no issue under /home directories.

**Comment by vcprocles** [comment]
It seems to be a problem with Snap which I don't really know how to fix.

Try opening your files using File -> Open, this works fine on my device.

I'm going to look into making a Flatpak package in hopes it would be less glitchy. 
And this also should be more convenient for users of Ubuntu-based distros which remove snapd by default (like Mint or Elementary).

**Comment by nhtctn** [comment]
I had tried File -> Open but i couldn't find other drives. But i figured out it was my mistake. The drive files can be reached from /home/media/username path. I open from there, and save button works just fine. After that even if i open subtitle with just clicking, it worked normally. So there is no issue now. Thank you for advice. And for your effort to make linux snap of course.

But an alternative installation method without snap would be nice indeed.
