### ISSUE TITLE
aegisub-procles 3.3.3-snap5a crashes when loading video

### ISSUE THREAD

**Issue by HobbyFreak** [vcprocles/aegisub-procles-snap#8]
I am a user of the aegisub-procles snap and I'd like to report the following issue:

aegisub-procles crashes when loading video
Version: 3.3.3-snap5a (24 September 2023)
Environment: Xubuntu 22.04
Video: h264 avc / aac / mkv

Temp solution:
- Revert to previous version 3.3.3-snap5
- temporary hold all updates for aegisub-procles

Hope this helps!

Thanks for maintaining this snap. It is a lifesaver!

**Comment by vcprocles** [comment]
Noticed this myself right now. Rolling back the update in Snap Store, nothing substantial was changed anyway

**Comment by vcprocles** [comment]
Rolled back to the old version in store

**Comment by HobbyFreak** [comment]
Thanks for changing this in Snap Store so fast!
